import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/storeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      
      <body className="min-h-full flex flex-col">
        <StoreProvider>          
        <Header />
        {children}
      </StoreProvider>
      </body>
    </html>
  );
}
