import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/storeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className="bg-bg-dark">
        
        <StoreProvider> 
              <div className="sticky top-0 z-50"> 
        <Header  />
        </div>  
        {children}
      </StoreProvider>
      
      </body>
    </html>
  );
}
